### ISSUE TITLE
Anzahl der Abschnitte werden vom Templatecourse nicht übernommen

### ISSUE THREAD

**Issue by relecand** [sudile/moodle-local_usercourses#4]
Im neu angelegten stud. Arbeitskurs ist die Anzahl der Abschnitte auf 5 (bzw. je nach Kursgrundeinstellung des Moodle) eingestellt, obwohl der Templatekurs nur 2 Abschnitte hat.

**Comment by jojoob** [comment]
fixed with 992ebc5142910794e541ea34c21928ed1f7b8bbc
