### ISSUE TITLE
Blöcke: Std.-Blöcke nicht anzeigen

### ISSUE THREAD

**Issue by relecand** [sudile/moodle-local_usercourses#5]
Im neu angelegten stud. Arbeitskurs sind neben den im Templatekurs eingestellten Blöcken auch noch die Std-Blocke von neu angelegten Kursen zu finden. Diese sollten dort nicht erscheinen.

**Comment by jojoob** [comment]
Habe den Restore Prozess umgeschrieben. In meinen Tests hat es jetzt funktioniert.
